[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1

[[services]]
name = "web"
protocol = "http"
port = "8000" 